import { Router } from 'express';
import * as ctrl from '../controllers/automations.js';
const r = Router();
r.get('/',  ctrl.list);
r.get('/:type',  ctrl.getOne);
r.patch('/:type',  ctrl.update);
r.post('/:type/reset',  ctrl.reset);
r.get('/stats/summary',  ctrl.stats);
r.post('/preview',  ctrl.preview);
export default r;
