import { Router } from 'express';
import * as ctrl from '../controllers/discounts.js';
const r = Router();
r.get('/',  ctrl.list);
r.get('/validate/:code',  ctrl.validate);
r.get('/campaign/:code',  ctrl.campaign);
r.get('/apply-url',  ctrl.applyUrl);
r.get('/search',  ctrl.search);
r.get('/conflicts',  ctrl.conflicts);
export default r;
