import { Router } from 'express';
import { rlReportsOverview, rlReportsGeneral, rlReportsExport } from '../middlewares/rateLimits.js';
import * as ctrl from '../controllers/reports.js';
const r = Router();
r.get('/overview', rlReportsOverview,  ctrl.overview);
r.get('/campaigns', rlReportsGeneral,  ctrl.campaigns);
r.get('/campaigns/:id', rlReportsGeneral,  ctrl.campaignById);
r.get('/automations', rlReportsGeneral,  ctrl.automations);
r.get('/messaging', rlReportsGeneral,  ctrl.messaging);
r.get('/revenue', rlReportsGeneral,  ctrl.revenue);
r.get('/export', rlReportsExport,  ctrl.exportData);
export default r;
